preEnv:
	mkdir build
client: clientTest.cpp
	g++ clientTest.cpp ../P2P/p2p.cpp -o ./build/client -I ../P2P
server: serverTest.cpp
	g++ serverTest.cpp ../P2P/p2p.cpp -o ./build/client -I ../P2P
clean:
	rm ./build/* -rf